gravity-ui/uikit

.github/workflows/release.yml

Update CHANGELOG.md and bump version automatically.

ci: add new workflow for releasing packages

---

src/components/Table/Table.tsx
src/components/Table/__stories__/Table.stories.tsx
src/components/Table/hoc/withTableSelection/withTableSelection.tsx
src/components/Table/hoc/withTableSettings/withTableSettings.tsx

* remove linear complexity from getRowId function in a compatible way
* add enhanced columns memoization to table with settings hoc
* cache css styles for cells.

perf: small Table performance fixes

---

package.json
src/components/ClipboardButton/ClipboardButton.tsx

CopyToClipboard component expects in its prop children a function that returns an element with the onClick prop. span has such a prop.
Fixes #45

fix: ClipboardButton

---

src/components/Dialog/ButtonClose/ButtonClose.scss
src/components/Dialog/ButtonClose/ButtonClose.tsx
src/components/Dialog/Dialog.scss
src/components/Dialog/Dialog.tsx
src/components/Dialog/DialogBody/DialogBody.scss
src/components/Dialog/DialogBody/DialogBody.tsx
src/components/Dialog/DialogDivider/DialogDivider.scss
src/components/Dialog/DialogDivider/DialogDivider.tsx
src/components/Dialog/DialogFooter/DialogFooter.scss
src/components/Dialog/DialogFooter/DialogFooter.tsx
src/components/Dialog/DialogHeader/DialogHeader.scss
src/components/Dialog/DialogHeader/DialogHeader.tsx
src/components/Dialog/README.md
src/components/Dialog/__stories__/Dialog.stories.tsx
src/components/Dialog/__stories__/DialogShowcase.tsx
src/components/Dialog/index.ts
src/components/index.ts

add Dialog component
add Readme in English

feat: migrate Dialog component

---

src/components/Toaster/README.md
src/components/Toaster/Toast/Toast.scss
src/components/Toaster/Toast/Toast.tsx
src/components/Toaster/Toaster.tsx
src/components/Toaster/ToastsContainer/ToastsContainer.scss
src/components/Toaster/ToastsContainer/ToastsContainer.tsx
src/components/Toaster/__stories__/Toaster.stories.tsx
src/components/Toaster/__stories__/ToasterShowcase.scss
src/components/Toaster/__stories__/ToasterShowcase.tsx
src/components/Toaster/constants/constants.scss
src/components/Toaster/index.ts
src/components/icons/AttentionToast.tsx
src/components/icons/SuccessToast.tsx
src/components/index.ts

add Toaster component
add Readme in English

feat: migrate Toaster component

---

src/components/Progress/Progress.scss
src/components/Progress/Progress.tsx
src/components/Progress/README.md
src/components/Progress/__stories__/Progress.stories.tsx
src/components/Progress/index.ts
src/components/index.ts

- add Progress component
- translate readme and comments
[Preview link](https://storybook-static.website.yandexcloud.net/uikit/pulls/42/?path=/docs/components-progress--default)

feat: migrate Progress component

---

jest.config.js
src/components/ClipboardButton/ClipboardButton.tsx
src/components/ClipboardButton/FakeButton.tsx
src/components/ClipboardButton/__tests__/ClipboradButton.test.tsx
src/components/utils/useActionHandlers.ts
src/components/utils/useButtonHandlers.ts

Add focus and keyboard handlers to `<ClipboardButton/>`

feat(ClipboardButton): improve a11y

---

README.md
src/components/Skeleton/Skeleton.scss
src/components/Skeleton/Skeleton.tsx
src/components/Skeleton/__stories__/SkeletonShowcase.tsx

Solves #96 
I have also added z-index so wave does not appear over rounded edges 
Before
After

feat(Skeleton): inline styles

---

.storybook/decorators/withMobile.tsx
package-lock.json
package.json
src/components/mobile/MobileProvider.tsx

refactor: remove react-router-dom dependency

---

src/components/Select/README.md
src/components/Select/Select.tsx
src/components/Select/__stories__/SelectShowcase.scss
src/components/Select/__stories__/SelectShowcase.tsx
src/components/Select/__stories__/constants.ts
src/components/Select/components/SelectControl/SelectControl.tsx
src/components/Select/components/SelectPopup/SelectPopup.scss
src/components/Select/components/SelectPopup/SelectPopup.tsx
src/components/Select/types.ts
src/components/Select/utils.ts

feat(Select): improvements

---

src/components/Select/README.md

Fix `onOpenChange` and `renderControl` properties description

fix(Select): fix readme

---

src/components/Tabs/Tabs.scss

Returned white-space property to Tabs title-item

fix(Tabs): add white-space property

---

src/components/Toaster/Toast/Toast.scss

Fix toasts background color.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix(Toaster): fix toasts bg color

---

src/components/Menu/MenuItem.tsx

fix: menu item qa prop

---

src/components/Modal/Modal.scss
src/demo/colors/Base.tsx
styles/colors/base/dark.scss
styles/colors/base/light.scss
styles/colors/private/dark.scss
styles/colors/sfx/dark.scss

feat(Modal): color updates

---

src/components/Popover/Popover.tsx

feat: popover applies actual visibility on autoclosable true

---

src/components/TextInput/TextInput.scss

Clear cross was too close to the right border on l and xl sizes.
This PR:
Sets padding for cross depending on size.

fix(TextInput): set paddings for clear cross depending on size

---

src/components/Toaster/Toast/Toast.scss
src/components/Toaster/Toast/Toast.tsx

Toasts close was broken in #144

fix(Toast): remove on close

---

src/components/List/components/SimpleContainer.tsx
src/components/RadioButton/RadioButton.tsx
src/components/Table/hoc/withTableSettings/withTableSettings.tsx
src/components/Tabs/Tabs.tsx
src/components/mobile/withMobile.tsx
src/components/theme/ThemeProvider.tsx
src/components/theme/withTheme.tsx
src/components/theme/withThemeValue.tsx
src/components/utils/PortalProvider.tsx
src/demo/Showcase/Showcase.tsx

chore: support `react@18` typings

---

src/components/Breadcrumbs/README.md

docs(Breadcrumbs): translate to english

---

src/components/Checkbox/README.md
src/components/ClipboardButton/README.md
src/components/CopyToClipboard/README.md
src/components/Label/README.md
src/components/Radio/README.md
src/components/RadioButton/README.md
src/components/Skeleton/README.md
src/components/Spin/README.md
src/components/Switch/README.md
src/components/User/README.md

docs: translate to english

---

src/components/Icon/Icon.tsx

feat(Icon): deprecate `onClick`

---

.github/workflows/ci.yml

chore: add `react@18` typecheck

---

src/components/Checkbox/__tests__/Checkbox.test.tsx

This PR:
Adds tests for Checkbox component.
Closes #77

test(Checkbox): Add Checkbox tests

---

src/components/TextInput/__stories__/TextInputShowcase.tsx

Added resize case to TextInput storybook

chore(TextInput): add resize case to storybook

---

src/components/Switch/README.md
src/components/Switch/__tests__/Switch.test.tsx

test(Switch): add tests

---

src/components/Button/Button.tsx
src/components/RadioButton/RadioButton.scss
src/components/RadioButton/RadioButtonOption.tsx
src/components/RadioButton/__stories__/RadioButtonShowcase.tsx
src/components/utils/common.ts

fix(RadioButton): fix option icon styles

---

package.json
src/components/List/components/ListItem.tsx
src/components/List/components/SimpleContainer.tsx
src/components/List/constants.ts
src/components/List/index.tsx
src/components/Select/README.md
src/components/Select/Select.tsx
src/components/Select/__tests__/Select.base-actions.test.tsx
src/components/Select/__tests__/base-actions.test.tsx
src/components/Select/components/SelectControl/SelectControl.tsx
src/components/Select/components/SelectPopup/SelectPopup.tsx
src/components/Select/constants.ts
src/components/Select/index.ts
src/components/Select/types.ts

test(Select): add base actions tests

---

src/components/Tooltip/Tooltip.tsx
src/components/utils/setRef.ts
src/components/utils/useForkRef.ts

fix(Tooltip): correctly set ref

---

src/components/Select/__stories__/SelectShowcase.tsx
src/components/Select/__tests__/utils.ts
src/components/Toaster/ToasterSingleton.tsx

fix: use directly import from lodash

---

CHANGELOG.md
package-lock.json
package.json
src/components/Label/Label.scss
src/components/Label/__stories__/Label.stories.scss
src/components/Label/__stories__/Label.stories.tsx
styles/brand.scss
styles/colors/base/dark-hc.scss
styles/colors/base/light-hc.scss
styles/colors/text/dark-hc.scss
styles/colors/text/light-hc.scss

This PR backports two sets of fixes for high-contrast themes from v3:
- #355
- #356

fix: backport hc fixes from v3

---

src/components/Select/utils.ts

fix(Select): prevent page scrolling after first click

---

src/components/Card/Card.tsx

Added missed React.forwardRef for Card component

feat: added React.forwardRef for Card

---

src/components/Table/README.md
src/components/Table/hoc/withTableSelection/withTableSelection.tsx

https://preview.yandexcloud.dev/uikit/374/?path=/story/components-table--hoc-with-table-selection

feat(Table): add possibility to range select with shift key pressed

---

package-lock.json
package.json
src/components/ClipboardButton/ClipboardButton.tsx
src/components/ClipboardButton/README.md
src/components/CopyToClipboard/CopyToClipboard.tsx
src/components/CopyToClipboard/types.ts

Added the ability to pass options to the clipboard component. Now the default copy format in the library `text/html` and therefore plain text can be copied with extra tags (For plain text it's needed to specify `text/plain` format in `options`)

feat(CopyToClipboard): add options

---

src/components/Label/Label.scss
src/components/Label/Label.tsx
src/components/Label/__stories__/Label.stories.tsx

- change hover style for label with copy: [Storybook](https://preview.yandexcloud.dev/uikit/351/?path=/story/components-label--interactions)
- fix label with a single icon: [Storybook](https://preview.yandexcloud.dev/uikit/351/?path=/story/components-label--icon)

fix(Label): change hover style for label with copy, fix label with single icon

---

src/components/DropdownMenu/DropdownMenu.tsx
src/components/DropdownMenu/DropdownMenuPopup.tsx
src/components/DropdownMenu/types.ts

feat(DropdownMenu): allow `<DropdownMenu.Item/>` w/out `action`

---

src/components/Toaster/Provider/ToasterProvider.tsx
src/components/Toaster/ToasterSingleton.tsx
src/components/Toaster/hooks/useToaster.ts
src/components/Toaster/index.ts
src/components/Toaster/types.ts

feat(Toaster)!: remove singleton instantiation

---

src/components/Label/Label.scss
src/components/Label/Label.tsx

- fix button color on hover/active
- remove extra div wrapper on type=copy

fix(Label): various fixes

---

src/components/Tabs/Tabs.scss
src/components/Tabs/Tabs.tsx
src/components/Tabs/TabsItem.tsx
src/components/Tabs/__stories__/Tabs.stories.tsx

* add `ref` to `<Tabs/>`
* add `extraProps` and `hasOverflow` to `<TabItem/>`

feat(Tabs): new features

---

src/components/Popover/Popover.tsx

feat(Popover)!: make `forceLinksAppearance` false by default

---

src/components/TextInput/InputControl/InputControl.tsx
src/components/TextInput/TextInput.scss
src/components/TextInput/TextInput.tsx
src/components/TextInput/__stories__/TextInputShowcase.scss
src/components/TextInput/__stories__/TextInputShowcase.tsx
src/components/TextInput/__tests__/TextInput.test.tsx
src/components/TextInput/types.ts
src/components/utils/useElementSize.ts

add ability to show inner label in InputControl variant of TextInput

feat(TextInput): ability to show innerLabel in InputControl

---

src/components/TextInput/TextInput.tsx

fix(TextInput): do not auto generate id for input if not needed

---

src/components/Label/Label.scss

fixed typos in the styles file

fix(Label): the Label with the close button style fix

---

src/components/Select/Select.tsx
src/components/Select/__stories__/Select.stories.tsx
src/components/Select/components/SelectControl/SelectControl.scss
src/components/Select/components/SelectControl/SelectControl.tsx
src/components/Select/components/SelectList/SelectList.scss
src/components/Select/components/SelectPopup/SelectPopup.tsx
src/components/Select/types.ts
src/components/Select/utils.tsx

feat(Select): add error property

---

src/components/RadioButton/RadioButton.tsx
src/components/RadioButton/__tests__/RadioButton.test.tsx

Check all basic props.
A lot of tests are similar to RadioGroup components.
Closes #78

test(RadioButton): add tests

---

src/components/Select/Select.tsx
src/components/Select/components/SelectControl/SelectControl.tsx
src/components/Select/types.ts

Added passing Select value to renderControl function due to this makes it easier to render selected values in own control

feat(Select): add support selected value in renderControl

---

src/components/DropdownMenu/DropdownMenuItem.tsx
src/components/utils/useListNavigation/useListNavigation.ts

- removed required path from DropdownMenuItemProps
- fixed navigation of no items available

fix(DropdownMenu): remove required path from DropdownMenuItemProps, fix navigation

---

src/components/theme/index.ts

[theme] export `RealTheme` and `ThemeType` types

---

src/components/Stories/README.md
src/components/Stories/Stories.tsx
src/components/Stories/__stories__/Stories.stories.tsx
src/components/Stories/components/StoriesLayout/StoriesLayout.scss
src/components/Stories/components/StoriesLayout/StoriesLayout.tsx

Added single page stories support
Added possibility to provide custom controls
Added possibility to add custom styles for stories modal contents

feat(Stories): support single page story

---

src/components/index.ts
src/components/utils/LayerManager.ts

See https://github.com/gravity-ui/uikit/pull/492 for prequel

feat(LayerManager): add a way to subscribe to stack changes

---

src/components/Menu/Menu.scss

fix(Menu): group label style

---

src/components/Button/Button.scss
styles/colors/text/dark-hc.scss
styles/colors/text/dark.scss
styles/colors/text/light-hc.scss
styles/colors/text/light.scss

https://github.com/gravity-ui/uikit/issues/725

fix(Button): use `--yc-color-text-special` var for all themes

---

src/components/SharePopover/SharePopover.tsx

feat(SharePopover)!: remove deprecated `handleMetrika` prop

---

package-lock.json
package.json
src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Table/Table.tsx
src/components/utils/useElementSize.ts
test-utils/setup-tests.ts

feat!: remove `resize-observer-polyfill`

---

src/components/Progress/Progress.scss
src/components/Progress/Progress.tsx
src/components/Progress/README.md
src/components/Progress/__stories__/Progress.stories.tsx

feat(Progress)!: rename `view` prop to `size`

---

src/components/Alert/Alert.scss
src/components/Alert/Alert.test.tsx
src/components/Alert/Alert.tsx
src/components/Alert/AlertActions.tsx
src/components/Alert/AlertIcon.tsx
src/components/Alert/AlertTitle.tsx
src/components/Alert/__snapshots__/Alert.test.tsx.snap
src/components/Alert/__stories__/Alert.mdx
src/components/Alert/__stories__/Alert.stories.tsx
src/components/Alert/__stories__/examples/index.tsx
src/components/Alert/constants.ts
src/components/Alert/index.ts
src/components/Alert/types.ts
src/components/Card/Card.tsx
src/components/index.ts

Just new component for interface.
Start review from `docs` section in Storybook
related to DATAUI-1590

feat(Alert): added new component Alert

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.tsx
src/components/Popover/components/Trigger/Trigger.tsx

fix: change span to div in popover

---

src/components/Popover/Popover.scss
src/components/Popover/Popover.tsx
src/components/Popover/components/Trigger/Trigger.tsx

It was breaking change
Reverts gravity-ui/uikit#748

fix: revert "fix: change span to div in popover"

---

styles/themes/common/_index.scss

feat!: update `xs` border radius

---

.eslintrc
src/components/Card/Card.tsx
src/components/Card/__tests__/Card.test.tsx
src/components/utils/useActionHandlers.ts

fix(Card): prevent keyboard handler form abort

---

src/components/Select/__tests__/getSelectedOptionsContent.test.ts
src/components/Select/utils.tsx

Co-authored-by: Yevhenii Chernovol <echernovol@yandex-team.ru>

feat(Select): selected values appearance

---

src/components/Select/README.md
src/components/Select/Select.tsx
src/components/Select/__stories__/SelectShowcase.tsx
src/components/Select/__stories__/constants.ts
src/components/Select/__tests__/Select.popup.test.tsx
src/components/Select/components/SelectList/GroupLabel.tsx
src/components/Select/components/SelectList/SelectList.scss
src/components/Select/components/SelectList/SelectList.tsx
src/components/Select/types.ts
src/components/Select/utils.tsx

Add prop getOptionGroupHeight in Select, cause no way to change it.

feat(Select): add  renderOptionGroup, getOptionGroupHeight props

---

src/components/Select/Select.tsx

Co-authored-by: Yevhenii Chernovol <echernovol@yandex-team.ru>

fix(Select): disable option selection <pick>

---

src/components/Loader/README.md

Update README for Loader component

docs(Loader): update README

---

src/components/Loader/README.md
src/components/Spin/README.md

Update README for Spin component

docs(Spin): update README

---

src/components/Skeleton/README.md

Update README for Skeleton component

docs(Skeleton): update README

---

package-lock.json
package.json
src/components/Breadcrumbs/__stories__/BreadcrumbsShowcase.tsx
src/components/Button/__stories__/ButtonShowcase.tsx
src/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx
src/components/Label/__stories__/Label.stories.tsx
src/components/Label/__stories__/LabelShowcase.tsx
src/components/List/__stories__/ListShowcase.tsx
src/components/RadioButton/__stories__/RadioButtonShowcase.tsx
src/components/Sheet/__stories__/DefaultShowcase/DefaultShowcase.stories.tsx
src/components/Sheet/__stories__/WithMenuShowcase/WithMenuShowcase.stories.tsx
src/components/Skeleton/__stories__/SkeletonShowcase.tsx
src/components/controls/TextArea/__stories__/TextAreaShowcase.tsx
src/components/controls/TextInput/__stories__/TextInputShowcase.tsx
src/components/utils/cn.ts
src/demo/DocsDecorator/DocsDecorator.tsx
src/demo/DocsExample/DocsExample.tsx
src/demo/Showcase/Showcase.tsx
src/demo/ShowcaseItem/ShowcaseItem.tsx
src/demo/colors/ColorTable.tsx
src/demo/typography/TextPanel.tsx
src/globals.d.ts
src/stories/Branding/BrandingConfugurator/BrandingConfigurator.tsx
src/stories/Branding/PaletteGenerator/PaletteGenerator.tsx

change `bem-cn-lite` to `@bem-react/classname`

refactor: migrate to `@bem-react/classname`

---

src/components/CopyToClipboard/README.md

Update README for `CopyToClipboard` component

docs(CopyToClipboard): update README

---

src/components/ClipboardIcon/README.md
src/components/CopyToClipboard/README.md

Update README for `ClipboardIcon` component

docs(ClipboardIcon): update README

---

src/components/Progress/README.md

docs(Progress): update readme

---

src/components/Popup/Popup.tsx
src/components/Popup/README.md
src/components/Portal/README.md

Also added docs for Portal component

docs(Popup): add readme

---

src/components/Checkbox/README.md
src/components/Radio/README.md
src/components/RadioButton/README.md
src/components/RadioGroup/README.md
src/components/Switch/README.md

https://github.com/gravity-ui/uikit/issues/861

docs(Checkbox, Radio, RadioGroup, RadioButton): update Readme

---

src/components/layout/Flex/Flex.tsx
src/components/layout/hooks/useLayoutContext.ts
src/components/layout/types.ts

feat(Flex): add alignContent, justifyItems and justifySelf css props

---

src/components/Link/README.md
src/components/Link/__stories__/Link.mdx
src/components/Link/__stories__/examples/LinkExampleView/LinkExampleView.tsx

PR to landing https://github.com/gravity-ui/landing/pull/81

docs(Link): added README.md for landing

---

src/components/Pagination/README.md

docs(Pagination): update README

---

src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/BreadcrumbsItem.tsx
src/components/Breadcrumbs/__stories__/BreadcrumbsShowcase.tsx
src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx

Make available setting custom title for breadcrumb item

feat(Breadcrumbs): add `title` prop to item

---

src/components/Hotkey/README.md

docs(Hotkey): add readme

---

src/components/Alert/README.md

Brang corrections to English, introduced in https://st.yandex-team.ru/CLOUDLOC-927

docs(Alert): corrections of component documentation

---

src/components/Toc/README.md
src/components/Toc/Toc.tsx
src/components/Toc/__stories__/Toc.stories.scss
src/components/Toc/__stories__/Toc.stories.tsx

docs(Toc): add component docs

---

src/components/Select/types.ts

fix(Select): fix SelectRenderControlProps.onClick type

---

src/components/Button/Button.scss
src/components/Button/README.md
src/components/Button/__stories__/Button.stories.tsx
src/components/ClipboardButton/ClipboardButton.scss
src/components/ClipboardButton/ClipboardButton.tsx
src/components/Label/Label.scss
src/components/Select/components/SelectClear/SelectClear.scss
src/components/controls/TextArea/TextArea.scss
src/components/controls/TextInput/TextInput.scss
src/components/controls/TextInput/TextInput.tsx
src/components/controls/common/ClearButton/ClearButton.scss
styles/mixins.scss

- Removed old css variables (BREAKING)
- Added new CSS API
- Significantly reduced Button's CSS size

feat(Button)!: add CSS API

---

src/components/Breadcrumbs/Breadcrumbs.scss
src/components/Button/Button.scss
src/components/Card/Card.scss
src/components/Checkbox/Checkbox.scss
src/components/Disclosure/Disclosure.scss
src/components/Link/Link.scss
src/components/Menu/Menu.scss
src/components/Radio/Radio.scss
src/components/RadioButton/RadioButton.scss
src/components/Switch/Switch.scss
src/components/Tabs/Tabs.scss
src/components/Toc/TocItem/TocItem.scss

feat!: remove focus visible fallback

---

gulpfile.js

feat!: add css imports to cjs files

---

src/components/Toaster/Toast/Toast.scss
src/components/Toaster/Toast/Toast.tsx
src/components/Toaster/__stories__/Toaster.stories.tsx
src/components/Toaster/__stories__/ToasterShowcase.tsx

fix(Toast): fix overflows

---

src/components/Tooltip/Tooltip.tsx

feat(Tooltip): add `disablePortal` prop

---

src/components/Checkbox/README.md

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

docs: update checkbox docs

---

src/components/Select/Select.tsx
src/components/Select/__tests__/Select.base-actions.test.tsx
src/constants.ts

Keyboard interaction in select components does not match specification:  https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#keyboard_interaction
META DATA: FORMS-11544

fix(Select): update keyboard interaction to correspond with specification

---

src/components/controls/TextArea/__tests__/TextArea.test.tsx
src/components/controls/TextInput/__tests__/TextInput.input.test.tsx
src/components/controls/common/ClearButton/i18n/en.json
src/components/controls/common/ClearButton/i18n/ru.json

fix(a11y): make a short text for the clear button

---

src/components/Popup/Popup.tsx
src/components/Popup/README.md

feat(Popup): add `aria-label` & `aria-labelledby` attributes

---

src/components/controls/TextInput/AdditionalContent.tsx
src/components/controls/TextInput/TextInput.scss
src/components/controls/TextInput/TextInput.tsx

feat(TextInput): support rtl

---

src/components/Select/components/SelectControl/SelectControl.scss

fix(Select): fix wrong view "clear" styles

---

src/components/Button/Button.scss

fix(Button): fix disabled raised view style

---

src/components/Table/README.md

Small fix for examples docs
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en

docs(Table): typos in examples

---

src/components/Select/components/SelectList/SelectList.scss

fix(Select): add 100% width to default labels

---

src/components/Pagination/Pagination.tsx
src/components/Pagination/utils.ts

fix(Pagination): fix total page calculation

---

src/components/Select/components/SelectClear/SelectClear.tsx

Issue: [#1249](https://github.com/gravity-ui/uikit/issues/1249)

fix(Select): add type="button" to SelectClear

---

src/components/Dialog/ButtonClose/ButtonClose.scss
src/components/Dialog/Dialog.scss
src/components/Dialog/DialogBody/DialogBody.scss
src/components/Dialog/DialogDivider/DialogDivider.scss
src/components/Dialog/DialogFooter/DialogFooter.scss
src/components/Dialog/DialogHeader/DialogHeader.scss
src/components/List/List.scss
src/components/List/README.md
src/components/List/__stories__/ListShowcase.scss
src/components/List/__stories__/ListShowcase.tsx
src/components/Table/hoc/withTableSettings/TableColumnSetup/TableColumnSetup.scss
src/components/Table/hoc/withTableSettings/TableColumnSetup/TableColumnSetup.tsx

List and Dialog variables removed/replaced by CSS API

refactor!: remove remaining `--yc-*` variables

---

.storybook/decorators/withMobile.tsx
.storybook/decorators/withStrictMode.tsx
.storybook/decorators/withTheme.tsx
.storybook/preview.tsx
src/components/Pagination/Pagination.tsx
src/components/Select/Select.tsx
src/components/Toaster/ToasterComponent/ToasterComponent.tsx
src/components/mobile/MobileContext.ts
src/components/mobile/MobileProvider.tsx
src/components/mobile/useMobile.ts
src/components/mobile/usePlatform.ts
src/components/mobile/withMobile.tsx

Same change that we did with theme context
Closes #1241

feat!: remove setters from mobile hooks

---

src/components/Pagination/__stories__/Pagination.stories.tsx

fix(Pagination): stories controls

---

src/components/Table/Table.scss

feat(Table)!: update cell paddings

---

src/components/Table/Table.scss

fix(Table): sticky column

---

src/components/Label/Label.tsx
src/components/Label/README.md
src/components/UserLabel/README.md
src/components/UserLabel/UserLabel.tsx
src/components/UserLabel/__stories__/UserLabel.stories.tsx
src/components/UserLabel/__tests__/UserLabel.test.tsx
src/components/UserLabel/types.ts

onClose was a bad naming, it has nothing to do with closing

feat!: rename onClose to onCloseClick

---

src/components/TreeSelect/TreeSelectItem/TreeSelectItem.tsx
src/components/TreeSelect/__stories__/components/WithGroupSelectionControlledStateAndCustomIcon.tsx
src/components/TreeSelect/__stories__/components/WithItemLinksAndActionsExample.tsx
src/components/useList/__stories__/components/FlattenList.tsx
src/components/useList/components/ListItemView/ListItemView.scss
src/components/useList/components/ListItemView/ListItemView.tsx
src/components/useList/components/ListItemView/__stories__/ListItemView.stories.tsx

- fix default crop behaviour;
- added more examples with `ListItemView` to storybook;
CLOUDFRONT-24441

fix: rework new ListItemView text crop behaviour

---

src/components/ClipboardButton/ClipboardButton.tsx

This reverts commit e3162894e5488099caafa65461a9ae8ac8d95fa0.

Revert "feat(ClipboardButton): add view property (#1302)"

---

src/components/Menu/Menu.scss
src/components/Menu/MenuItem.tsx
src/components/Menu/__stories__/Menu.stories.tsx

Fix the styles for non-interactive menu items

fix(MenuItem): fix non interactive MenuItem style

---

src/components/index.ts

fix(Slider): add export for Slider

---

src/components/Alert/Alert.tsx
src/components/Alert/__stories__/Alert.stories.tsx

related to https://github.com/gravity-ui/uikit/issues/1384

feat(Alert): added ability to pass null as icon prop value

---

.github/workflows/release.yml

Similar workflow is already tested on `@gravity-ui/dialog-fields` library:
https://github.com/gravity-ui/dialog-fields/blob/main/.github/workflows/release.yml

chore(release.yaml): add branch pattern 'release/v*'

---

src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/Breadcrumbs/BreadcrumbsItem.tsx
src/components/Breadcrumbs/README.md
src/components/Breadcrumbs/__stories__/BreadcrumbsShowcase.tsx
src/components/Breadcrumbs/__tests__/Breadcrumbs.test.tsx
src/components/Breadcrumbs/types.ts

https://github.com/gravity-ui/uikit/issues/1287

feat(Breadcrumbs): add `renderItem` property

---

src/hooks/useActionHandlers/useActionHandlers.ts

fix(DropdownMenu): fix opening from keyboard

---

src/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx
src/components/DropdownMenu/__stories__/options.tsx
src/components/DropdownMenu/utils/toItemList.ts

fix(DropdownMenu): fix hiding group subitems

---

CODEOWNERS
src/components/Divider/Divider.scss
src/components/Divider/Divider.tsx
src/components/Divider/README.md
src/components/Divider/__stories__/Divider.stories.tsx
src/components/Divider/__stories__/Docs.mdx
src/components/Divider/__tests__/Divider.test.tsx
src/components/Divider/index.ts

feat(Divider): add the Divider component

---

src/components/Tooltip/Tooltip.scss

fix(Tooltip): fix appearing & disappearing

---

src/components/TreeSelect/TreeSelect.scss
src/components/TreeSelect/TreeSelect.tsx
src/components/useList/components/ListItemView/ListItemView.scss

feat(TreeSelect): rework popup border radius

---

src/components/TreeList/__stories__/TreeList.mdx
src/components/useList/__stories__/useList.mdx
src/components/useList/index.ts
src/unstable.ts

added imports for more convenient use

fix(useList): added missing imports to docs

---

src/components/Label/Label.scss
src/components/Label/Label.tsx
src/components/Label/__stories__/Label.stories.tsx

fix(Label): correctly work with keyboard

---

src/components/useList/components/ListItemView/ListItemView.scss

fixed styles for bg color of `ListItemView` component
about dragging element bg color more info here https://github.com/gravity-ui/rfc/issues/10#issuecomment-2039481000

fix(ListItemView): fix bg color

---

.storybook/test-runner.ts
src/components/Button/__stories__/Button.stories.tsx
src/components/Divider/__stories__/Divider.stories.tsx

- Fixed and ignored some a11y violations in stories
- Less log output from axe. Leaving only violations

ci(storybook): fix a11y issues

---

src/demo/colors/Base.tsx
styles/themes/dark-hc/base.scss
styles/themes/dark/base.scss
styles/themes/light-hc/base.scss
styles/themes/light/base.scss

feat: add new css variable `--g-color-base-float-medium`

---

src/components/controls/TextArea/TextArea.scss

style(TextArea): fix scrollbar borders

---

CODEOWNERS

@Estasie will continue to support the Link instead of me

chore(Link): change codeowner

---

.storybook/main.ts
package-lock.json
package.json

docs: add source code addon for storybook

---

src/components/Button/Button.scss

there is no loading effect of normal-contrast button

fix(Button): normal-contrast loading view

---

src/components/Toc/TocItem/TocItem.scss

fix(Toc): unify item line height

---

src/components/ArrowToggle/__stories__/ArrowToggle.stories.tsx
src/components/utils/__tests__/xpath.test.tsx

chore: fix a11y lint issues

---

src/components/Select/components/SelectClear/SelectClear.scss
src/components/Select/components/SelectControl/SelectControl.scss
src/components/Select/components/SelectControl/SelectControl.tsx

feat(Select): new label and value resize behaviour

---

src/components/TreeSelect/__stories__/Docs.mdx
src/components/TreeSelect/__stories__/TreeSelectDocs.md

simple docs to start with TreeSelect

docs(TreeSelect): simple docs to start

---

src/components/Table/hoc/withTableActions/withTableActions.tsx

#1834 
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru

feat(Table): add dynamic href support for row actions in withTableActions

---

src/components/Button/Button.tsx
src/components/Button/constants.ts
src/components/Toaster/Toast/Toast.scss
src/components/Toaster/__stories__/Toaster.stories.tsx
src/components/Toaster/constants.ts
src/components/Toaster/types.ts

Spacing from controls increased to 12px

fix(Toaster): change spacing before actions

---

styles/styles.scss

fix(styles): rules order in block

---

src/components/Toaster/ToastList/ToastAnimation.scss

fix(Toaster): reveal animation lag

---

styles/themes/common/typography.scss

feat(styles)!: change monospace fonts order

---

src/components/theme/ThemeProvider.tsx
src/components/theme/dom-helpers.ts
styles/mixins.scss
styles/styles.scss

feat!: move scrollbar styles to separate mixin

---

src/components/Button/Button.scss
src/components/Button/README.md

feat(Button)!: rename icon-size CSS API

---

src/components/Select/components/SelectList/OptionWrap.tsx

Added a title to the option element in the Select component
Issue #1922

feat(Select): add title for option

---

src/components/Select/types.ts
src/components/Select/utils.tsx

Passing custom values to `renderOptionGroup`

feat(Select): add data for option group

---

.github/workflows/pr-preview-deploy.yml
.github/workflows/pr-visual-tests-report.yml

Revert "ci: fix workflows uploading to s3"

---

src/components/Button/Button.tsx

Unfortunately typescript cannot determine which type is used when we
don't provide `href` property. As result it brings some compilation
errors with `ref` and `component` fields.
So we need to bring back the conditional inferring of props type.
It was a mistake to think we can avoid it.
Additionaly `Exclude<ElementType, 'a' | 'button'>` is extracted
as separate type `ButtonCustomElementType`

fix(Button): additional to #2070

---

src/components/FilePreview/FilePreview.scss
src/components/FilePreview/FilePreview.tsx
src/components/FilePreview/README.md
src/components/FilePreview/__stories__/FilePreview.stories.tsx

feat(FilePreview)!: change size of default image preview

---

src/components/Sheet/README.md
src/components/Sheet/Sheet.scss

Add `--g-sheet-background-color` variable

feat(Sheet): add background css api

---

src/components/theme/dom-helpers.ts

Cherry-pick https://github.com/gravity-ui/uikit/commit/5215fe4dbac816d0a155bf79407e2d78df73bd31

fix(ThemeProvider): do not update class name in case of null body

---

src/components/Dialog/DialogFooter/DialogFooter.tsx

fix(DialogFooter): ignore onClickButtonApply if button is in disabled or in loading state

---

src/components/Checkbox/Checkbox.scss
src/components/Checkbox/README-ru.md
src/components/Checkbox/README.md
src/components/Checkbox/__stories__/Checkbox.stories.tsx
src/components/Checkbox/__stories__/CheckboxShowcase.tsx
src/components/ControlLabel/ControlLabel.scss
src/components/ControlLabel/types.ts
src/components/Radio/README-ru.md
src/components/Radio/Radio.scss
src/components/Radio/__stories__/Radio.stories.tsx
src/components/Radio/__stories__/RadioShowcase.tsx
src/components/RadioGroup/README.md
src/components/RadioGroup/RadioGroup.scss
src/components/RadioGroup/__stories__/RadioGroup.stories.tsx

https://st.yandex-team.ru/STARTREK-53131

feat(Checkbox): add xl size

---

src/components/Table/Table.tsx
src/components/Table/__stories__/Table.stories.tsx
src/components/Table/hoc/withTableActions/withTableActions.tsx

feat(Table): add qa

---

src/components/Breadcrumbs/BreadcrumbsItem.tsx
src/components/DropdownMenu/DropdownMenuPopup.tsx
src/components/List/List.tsx
src/components/Palette/hooks.ts
src/components/utils/layer-manager/LayerManager.ts
src/constants.ts
src/hooks/useListNavigation/useListNavigation.ts

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/en/?lang=en.
Fixed issue https://github.com/gravity-ui/uikit/issues/2397.

refactor: use KeyCode in event handlers

---

src/components/mobile/index.ts
src/components/mobile/withPlatform.tsx

link to issue - https://github.com/gravity-ui/uikit/issues/2420

feat: add new hoc withPlatform
