gravity-ui/uikit

- src/components/variables.scss
Fix incorrect value used as classname selector. Current behaviour breaks view of the Tabs component.
> fix: root scss variable

- src/components/TextInput/TextInput.scss
Currently TextInput is always hiding textarea resize control, even when resize prop was specified in controlProps.
This fix modifies TextInput stylesheet so resize control will be hidden only when resize prop is missing or set to `none`.
> fix: correctly show textarea resize control

- src/components/List/List.tsx
Revert the breaking change https://github.com/yandex-cloud/uikit/commit/a3a3720fbc7960e6294a54e786e4adba11174918#diff-72874b9cecaf9f2c29fe3d4767351a1b799410f62b522a138b5e4f2fa6880171L329
> fix: allow not to set a fixed height for non-virtualized lists

- src/components/List/List.tsx
Fixed case: delayed call setState (triggered by mouseLeave) for unmounted component causes error
> fix (List): check mount status for delayed setState

- src/components/DropdownMenu/DropdownMenu.tsx
- src/components/DropdownMenu/DropdownMenuPopup.tsx
- src/components/DropdownMenu/README.md
- src/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx
- src/components/DropdownMenu/types.ts
Adds `size` property that affects both switcher and dropdown menu sizes.
If needed, sizes for switcher and menu, can be defined separately using `defaultMenuProps`(added by this PR) and `defaultSwitcherProps` (existing property).
Changes default button size: `"s"` -> `"m"`
Сloses #107
> feat(DropdownMenu): change default size in DropdownMenu

- src/components/Toaster/Toast/Toast.scss
Increase css specificity of close button mixin to avoid problem like this:
> fix(Toaster): increase css specificity of close button mixin

- src/demo/colors/Private.tsx
- styles/colors/private/dark.scss
- styles/colors/private/light.scss
- Updated private blue color
- Fixed private colors showcase: it was using old solid colors naming convention
> feat: update blue color

- src/components/Dialog/Dialog.tsx
- src/components/Dialog/README.md
- src/components/Modal/Modal.tsx
- src/components/Portal/Portal.tsx
- src/components/index.ts
- src/components/utils/PortalProvider.tsx
- src/components/utils/usePortalContainer.ts
allow display modals with a different root element. this may be useful in case when we need to determine the source of modals or place modals into container other than the document root. the default behaviour remains the same.
Example: (define the new modals root)
```
const ref = useRef();
<LayerProvider container={ref}>
...components where we need new root for modals
</LayerProvider>
<div ref={ref} className="modal-root"></div>
```
> feat: allow use layers for Dialog/Modal/Popup with different root

- src/components/utils/LayerManager.ts
Shadom DOM doesn't give you the correct element for `event.target` (it gives you the root for any click you make).
In our project (Yandex Nirvana) we use Shadom DOM and because of that the `isOutsideClick` function doesn't work correctly for us which messes up the `Popup` component which depends on it.
Use the `composedPath` function which gives you the path to the element you clicked, which works even in Shadow DOM, so we can use the `Popup` element without bugs.
You can read about the problem and solution here: https://stackoverflow.com/a/57963850/5892475.
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.
> fix: Correct target detection for shadow-dom in function isOutsideClick

- src/components/Radio/Radio.tsx
- src/components/Radio/__tests__/Radio.test.tsx
This PR:
- Adds tests for Radio component
- Moves `aria-hidden` attribute from input control (to access input simply by role `radio`)
Motivation:
* focusable element [is not recommend](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden#description) to have aria-hidden
* similar checkbox input [does not have](https://github.com/yandex-cloud/uikit/blob/main/src/components/Checkbox/Checkbox.tsx#L63) ones on itself 
Closes https://github.com/yandex-cloud/uikit/issues/80
> test(Radio): Add Radio tests

- CODEOWNERS
- src/components/theme/types.ts
Current value of `RealTheme` type is not compatible with some existing code in services and related libraries. I think it would be better to keep it as `string` for now and move to a more narrow type in the next major release.
> fix: relax RealTheme type for compatibility

- src/components/Text/Text.tsx
Add `title` property for `Text` component.
`title` is [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes), there is no conflicts with `as` property.
> chore: add title props for Text component

- src/components/Button/Button.scss
This happens because height is 34px, making it 150% (100% is not enough because of animation) fixes this issue and doesn't break how it looks in other browsers.
> fix: use background-size as percent value for loading button for safari

- src/components/utils/configure.ts
Instead of:
```ts
import {configure, Lang} from '@gravity-ui/uikit';
configure({lang: Lang.En});
```
it's able to write:
```ts
import {configure} from '@gravity-ui/uikit';
configure({lang: 'en'});
```
> fix: loose i18n typings

- src/components/Tooltip/Tooltip.tsx
In some cases, you may need to forcibly disable the display of the tooltip
> feat(Tooltip): add ability to disable display of the tooltip

- src/components/CopyToClipboard/README.md
There is no default value for `timeout` value. And both `timeout` and `text` are required.
This PR fixeds README.
It might be better to set some default value in the future.
> docs(CopyToClipboard): fix README props

- src/components/Popover/Popover.tsx
- src/components/Popover/index.ts
- src/components/Popover/types.ts
- src/components/Popup/Popup.tsx
- src/components/utils/usePopper.ts
The Popover component calls Popup internally. Updated the Popover props type so that it can accept the strategy prop and pass it to the Popup. In addition, replaced the Anchor property type so that a virtual anchor could be set. Also, in order to be able to type the transmitted value, created an exported Anchor type
> feat(Popover): updated anchorRef prop, added strategy prop to Popover

- src/components/Label/Label.scss
- src/components/Label/Label.tsx
- copy and close buttons are now available in all themes
- update hover styles of action button
[Storybook](https://preview.yandexcloud.dev/uikit/381/?path=/story/components-label--theme&args=type:copy;copyText:test)
> feat(Label): support action button in all themes

- src/components/List/List.scss
- src/components/List/components/ListItem.tsx
- src/components/Select/__stories__/SelectShowcase.tsx
- src/components/Select/__stories__/constants.ts
- src/components/Select/__tests__/Select.single.test.tsx
Changed strategy for disabling items in List component. We won't apply `pointer-events: none` therefore the component would be more flexible, e.g. it will be possible to add `<Tooltip />`component as a custom renderer for disabled items.
> feat(List): remove pointer-events from disabled items

- src/components/Menu/MenuItem.tsx
In case `<Menu.Item/>` got some elements with `pointer-events: all` clicks on such elements is propagated to `<Menu.Item>` `onClick` handler.
> fix(Menu.Item): remove `onClick` from disabled items

- src/components/Dialog/DialogFooter/DialogFooter.scss
There are cases when the Popup component can be applied to the button wrapper via the anchorRef attribute. In this case, the Popup is centred relative to the wrapper, and will be moved to the left due to the fact that the button contains an extra margin.
In general in the case when dialog with custom buttons renderer is used, the margin must be added by the user manually in the wrapper.
> fix(DialogFooter): updated button style

- src/components/mobile/MobileProvider.tsx
- src/components/mobile/constants.ts
- src/components/theme/ThemeProvider.tsx
- src/components/theme/updateBodyClassName.ts
- styles/styles.scss
On Android devices a custom scrollbar is not ignored, we need to disable it.
- MobileContext automatically adds the `yc-root_mobile` class.
- The existence of the `yc-root_mobile` or `yc-root_native-scrollbar` class disables the custom scrollbar.
> fix: use native scrollbar on mobile devices

- src/components/Label/Label.scss
- src/components/Label/Label.tsx
- src/components/Label/__stories__/Label.stories.tsx
- styles/brand.scss
- styles/styles.scss
I want to customize label for create new TagInput component with Label and TextInput collaboration
1. hasOnClick behaviour very strange only for default type
2. Fix Label component border radius as TextInput
3. Add correct XS, S, M sizes as TextInput component
> feat(Label)!: new xs size and click action for more custom label

- src/components/TextInput/TextInput.scss
textarea does not have resize attribute.
Revert "fix: correctly show textarea resize control"
Reverts yandex-cloud/uikit#33
> fix(TextInput)!: remove incorrect resize attribute styles

- src/components/HelpPopover/HelpPopover.scss
- src/components/HelpPopover/HelpPopover.tsx
Add css rule `left: 4` by default look like not so good solution.
What if i want render this Popover exactly in place? What if i want add padding with `padding` or `margin` rules?
And another important point is the evidence of behavior. How i should to know that this component is shifted on 4 pixels? 
Summing up the above i suggest remove this default offset at all and add the ability for users to manage the margins themselves
> feat(HelpPopup)!: remove default ofset

- src/components/List/List.tsx
- src/components/List/constants.ts
- src/components/constants.ts
If you enter something in the search field, a value deletion button will appear and it will be impossible to move to the next element using the Tab key, since the component intercepts pressing any key and blocks focus
> fix(List): remove focus from list on Tab key

- src/components/StoriesGroup/StoriesGroup.tsx
- src/components/StoriesGroup/components/StoriesPreview/StoriesPreview.scss
- src/components/StoriesGroup/components/StoriesPreview/StoriesPreview.tsx
Space between PreviewItems were disabled for user clicking and it is impossible to close StoriesGroup by clicking on area of PreviewItems
> fix(StoriesGroup): fix click area

- src/components/Table/__stories__/Table.stories.tsx
- src/components/Table/hoc/withTableActions/withTableActions.tsx
> feat(Table): pass click event to action handler

- src/components/Breadcrumbs/BreadcrumbsMore.tsx
- src/components/DropdownMenu/DropdownMenu.tsx
- src/components/DropdownMenu/DropdownMenuItem.tsx
- src/components/DropdownMenu/DropdownMenuPopup.tsx
- src/components/DropdownMenu/README.md
- src/components/DropdownMenu/__stories__/DropdownMenu.stories.tsx
- src/components/Text/Text.tsx
- src/components/Toaster/ToasterSingleton.tsx
- src/components/Toaster/ToasterSingletonReact18.tsx
- src/components/Toaster/types.ts
Removed deprecated props in `Toaster`, `Text` and `DropdownMenu`
> refactor!: remove deprecated props

- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/__stories__/RadioButton.stories.tsx
- src/components/RadioGroup/RadioGroup.tsx
- src/components/RadioGroup/__stories__/RadioGroup.stories.tsx
- src/components/types.ts
- src/components/utils/useRadioGroup.ts
> feat(RadioGroup): improve radio-group components a11y

- src/components/Portal/Portal.tsx
- src/components/utils/usePortalContainer.ts
In my Next.js app on SSR i a have an exception 
`
Server Error
ReferenceError: document is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
usePortalContainer
file:///..../node_modules/@gravity-ui/uikit/build/cjs/components/utils/usePortalContainer.js (9:68)
Portal
file:///..../node_modules/@gravity-ui/uikit/build/cjs/components/Portal/Portal.js (8:74)
`
> fix(Portal): add condition for default container for Portal

- src/components/Button/Button.tsx
- src/components/Link/Link.tsx
- src/components/List/components/ListItem.tsx
- src/components/Menu/MenuItem.tsx
- src/components/utils/useCheckbox.ts
- src/components/utils/useRadio.ts
- src/components/utils/withEventBrokerDomHandlers.tsx
Collecting events at the capture phase instead of the bubbling phase allows to get information before any effects occur on the event.
> feat(eventBroker): eventBroker acts in the bubbling phase

- src/components/Table/Table.tsx
- src/components/Table/__stories__/Table.stories.tsx
I had added an onMouseDown action for Table row to handle middle mouse button clicks and etc. OnClick works good at Safari and EI, but at Chromium ones we can handle MBC only throw onMouseDown
> feat(Table): add onMouseDown action for Table tr

- styles/colors/base/dark-hc.scss
Updated color value for base-generic-ultralight in dark-hc theme
> fix: base-generic-ultralight color in dark-hc theme

- styles/typography.scss
Request from designers: Menlo is looking better than SF Mono for our use-cases.
> feat(typography): do not use SF Mono

- src/components/Popover/Popover.scss
- src/components/Popover/__stories__/Popover.stories.tsx
Currently, the buttons with long text will just break the container
This pull request fixes this behavour by letting the buttons to wrap and to turn into a coloumn
> feat(Popover): let action and cancel buttons to wrap on long text

- src/components/Select/components/SelectControl/SelectControl.scss
Due to SelectControl label font-weight, label and value don't align correctly
Before
After
> fix(Select): align items by baseline for label and values

- src/components/layout/Col/Col.tsx
- src/components/layout/Container/Container.tsx
- src/components/layout/types.ts
There were some typos in docs/code comments ("mast" instead of "must")
By the way, there is [code spell checker plugin](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) for VSCode
---
I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=ru).
> docs: fixed typo in "must" word

- src/components/Select/utils.tsx
We had an issue with behaviour of filter in Select component. Problem is: it used String::match, which converted string argument into new RegEx without screening of functional characters, hence it crashed web page in case you type `[` or `(` into filter prompt.
> fix(Select): fixed behaviour of isOptionMatchedByFilter

- package.json
- src/components/index.ts
- src/components/layout/Col/Col.tsx
- src/components/layout/Col/__stories__/Col.stories.tsx
- src/components/layout/Container/Container.tsx
- src/components/layout/Container/__stories__/Container.stories.tsx
- src/components/layout/Container/useContainerThemeProps.ts
- src/components/layout/Flex/Flex.tsx
- src/components/layout/Flex/__stories__/Flex.stories.tsx
- src/components/layout/LayoutProvider/LayoutProvider.tsx
- src/components/layout/LayoutProvider/__stories__/Layout.docs.mdx
- src/components/layout/LayoutProvider/__stories__/Layout.stories.tsx
- src/components/layout/Row/Row.tsx
- src/components/layout/Row/__stories__/Row.stories.tsx
- src/components/layout/constants.ts
- src/components/layout/hooks/useLayoutContext.ts
- src/components/layout/spacing/spacing.tsx
- src/components/layout/types.ts
- remove `./unstable_layout` bundle
- remove unused section with common props in LayoutTheme. Now you need pass directly props in corresponding component (only `Container` now);
- added links to storybook docs from `jsdoc` on hover in each component
Note: may be in this pr should not remove `./unstable_layout` bundle and remove it on next major realease
> feat(Layout): stable version

- src/components/Label/Label.scss
- src/components/Label/Label.tsx
- src/components/Label/__stories__/Label.stories.scss
- src/components/Label/__stories__/Label.stories.tsx
in this pr
fixed: bad display of icon in 's' size labels
refactored: styles for different sizes
added: support for value prop + story for display all combinations of labels
> feat(Label): added value prop for "key:value" labels

- src/components/utils/useListNavigation/README.md
- src/components/utils/useListNavigation/useListNavigation.ts
Navigation with right/left arrows breaks the behaviour of cursor navigation,  so better to disable it for all the lists
> fix(useListNavigation): remove navigation with right and left arrows

- src/components/index.ts
- src/components/utils/LayerManager.ts
In order to create idle Popups in common, I need a way to determine in render-time whether current layer stack is empty (so that idle popup can start rendering). Even though I can subscribe to `layerschange` with event broker, there is no way to know if stack is initially empty.
> feat(LayerManager): export getLayersCount

- src/components/Table/hoc/withTableSelection/withTableSelection.tsx
Mutating `classNames` array with `push` can cause problems in cases where the `getRowClassNames` function isn't pure and gets it's return value from the outer scope.
e.g.
```ts
const classNames = ["foo-row"];
const getRowClassNames = () => classNames;
const TableWithSelection = withTableSelection(Table);
const Component = () => {
// ...
return <TableWithSelection {...props} getRowClassNames={getRowClassNames} />;
}
```
The example above results in rows having `row_selected` class even after being removed from `selectedIds`
> fix(Table): fix copying the array from getRowClassNames

- src/components/Toaster/Toast/Toast.tsx
otherwise it renders with an extra margin
> fix(Toast): don't render empty actions array

- src/components/DropdownMenu/README.md
This PR adapts the DropdownMenu's README.md for the landing website, as suggested in the [related issue](https://github.com/gravity-ui/uikit/issues/861).
> docs: adapt DropdownMenu readme for landing

- src/components/controls/TextInput/TextInput.scss
If `* {box-sizing: border-box}` style is applied then we got this:
> fix(TextInput): fix inside error display

- src/components/Skeleton/__stories__/Skeleton.stories.tsx
issue: https://github.com/gravity-ui/uikit/issues/969
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=ru.
> docs(Skeleton): default story is not visible

- src/components/Table/hoc/withTableSorting/withTableSorting.tsx
The method `isControlledState()` in this HOC is for determining whether the `sortState` is provided externally or not. It shouldn't turn off the whole sorting as it does in this case making the whole HOC useless.
> feat(withTableSorting): add control the use of data sorting

- src/components/Table/Table.scss
- src/components/Table/Table.tsx
- src/components/Table/hoc/withTableSelection/withTableSelection.scss
- src/components/Table/hoc/withTableSelection/withTableSelection.tsx
Issue: [#648](https://github.com/gravity-ui/uikit/issues/648)
> feat(Table): expand checkbox click area

- src/components/Alert/Alert.test.tsx
- src/components/Alert/AlertIcon.tsx
- src/components/Alert/__stories__/Alert.stories.tsx
- src/components/Alert/types.ts
- src/components/Card/Card.scss
- src/components/Card/Card.tsx
- src/components/Card/__tests__/Card.test.tsx
> feat!: rename theme prop `positive` -> `success`

- src/components/Tabs/Tabs.scss
Fixes #1048 
Before: 
After PR:
> fix(Tabs): tab outline focus is stripped

- src/components/Table/hoc/withTableSelection/withTableSelection.scss
Fixed a issue where when the table was stretched, the checkbox also started to stretch
> fix(Table): fixed checkbox max width

- src/components/Pagination/hooks/usePagination.ts
> fix(Pagination): fix wrong behaviour in case of 0 total

- src/components/Select/__stories__/SelectShowcase.tsx
- src/components/Select/utils.tsx
Issue: the `activateFirstClickableItem` is not working properly. It activates the item if it is in the first place and in the disabled state.
> fix(Select): activate first clickable item

- src/components/Alert/Alert.tsx
- src/components/Alert/AlertAction.tsx
- src/components/Alert/AlertActions.tsx
- src/components/Alert/AlertContext.tsx
- src/components/Alert/AlertContextProvider.tsx
- src/components/Alert/README.md
- src/components/Alert/__snapshots__/Alert.test.tsx.snap
- src/components/Alert/__stories__/Alert.stories.tsx
- src/components/Alert/index.ts
- src/components/Alert/types.ts
- src/components/Alert/useAlertContext.tsx
> feat(Alert): changed default Alert actions background

- src/components/Table/Table.tsx
This change was breaking. Colgroup doesn't take into account `box-sizing` property. We use `content-box`, but colgroup sets the width for the entire column, not only the content.
> fix: revert #831

- src/components/Text/README.md
- src/components/Text/Text.tsx
`id` often required to use with `aria-labelledby` attribute
> feat(Text): add `id` prop

- src/components/Table/hoc/withTableSorting/SortIndicator/SortIndicator.scss
- src/components/Table/hoc/withTableSorting/SortIndicator/SortIndicator.tsx
- src/components/Table/hoc/withTableSorting/withTableSorting.scss
- src/components/Table/hoc/withTableSorting/withTableSorting.tsx
- src/hooks/useActionHandlers/useActionHandlers.ts
Update view according to the `UXRFC-296`. Also added keyboard support for better a11y.
> feat(Table)!: update SortIndicator view

- src/components/Progress/Progress.tsx
- src/components/Progress/ProgressInnerText.tsx
- src/components/Progress/ProgressStackItem.tsx
- src/components/Progress/ProgressWithStack.tsx
- src/components/Progress/ProgressWithValue.tsx
- src/components/Progress/__stories__/Progress.stories.tsx
- src/components/Progress/constants.ts
- src/components/Progress/index.ts
- src/components/Progress/types.ts
- src/components/Progress/utils.ts
* splited to multiple simple components
* added React.forwardRef
> refactor(Progress): replaced class components by functional components

- src/components/Table/README.md
- src/components/Table/Table.tsx
- src/components/Table/__stories__/Table.stories.tsx
- src/components/Table/__tests__/Table.test.tsx
- src/components/Table/hoc/withTableActions/withTableActions.tsx
- src/components/Table/hoc/withTableSelection/withTableSelection.tsx
**Description of the problem**
The Table component now has several methods, each of which interacts with the display of the string -- getRowId, getRowClassNames, isRowDisabled.
It seems that it would be logical to make one method instead of 3, which will improve the user experience.
In the future, this method can be expanded, for example, you can add a description of whether the line should change the background on hover.
**The proposed solution**
Set up all 3 props, add a new one.
https://st.yandex-team.ru/UXRFC-393
> [WIP] feat(table): add getRowDescriptor property

- src/components/Table/__stories__/Table.stories.tsx
- src/components/Table/__stories__/utils.tsx
- src/components/Table/hoc/withTableSorting/withTableSorting.tsx
Just duplicate get logic from main Table code: https://github.com/gravity-ui/uikit/blob/main/src/components/Table/Table.tsx#L171
> fix(Table): withTableSorting can get sort value using column's ID written as path

- src/components/List/List.tsx
- src/components/List/__stories__/List.stories.tsx
- src/components/List/__stories__/ListWithLoader.scss
- src/components/List/__stories__/ListWithLoader.tsx
> fix(List): calling onLoadMore function while using keyboard

- src/components/Table/README.md
- src/components/Table/__stories__/Table.stories.tsx
- src/components/Table/hoc/withTableActions/withTableActions.tsx
> feat(Table): added link as Table action element

- src/components/Select/README.md
- src/components/Select/Select.tsx
- src/components/Select/__stories__/SelectShowcase.tsx
- src/components/Select/__tests__/Select.error.test.tsx
- src/components/Select/components/SelectControl/SelectControl.scss
- src/components/Select/components/SelectControl/SelectControl.tsx
- src/components/Select/i18n/en.json
- src/components/Select/i18n/ru.json
- src/components/Select/types.ts
> feat(Select): added errorMessage, errorPlacement and validationType props

- src/components/controls/TextInput/TextInput.scss
Hi
In some browsers (MIcrosoft Edge and others) we have encountered an issue where the input is autocompleted and displays the background outside of the input edges.
PS: Solving this problem by adding a border radius to the input doesn't work as expected, at least because it doesn't match the content radius.
| AS IS | TO BE | With radius |
|--------|--------|--------|
| <img width="664" alt="image" src="https://github.com/gravity-ui/uikit/assets/2071148/e37426e0-0454-4f82-acfa-ea3a1f5adfe8"> | <img width="664" alt="image" src="https://github.com/gravity-ui/uikit/assets/2071148/9c18fa44-482f-49b6-952c-89da8c0d4cda"> | <img width="664" alt="image" src="https://github.com/gravity-ui/uikit/assets/2071148/5d765c3e-42f0-4777-aa82-85253582b1c3"> |
> fix(TextInput): add overflow hidden to text-input__content wrapper

- src/components/TreeSelect/TreeSelect.tsx
- src/components/TreeSelect/__stories__/components/InfinityScrollExample.tsx
- src/components/TreeSelect/__stories__/components/RenderVirtualizedContainer.tsx
- src/components/TreeSelect/__stories__/components/WithDndListExample.tsx
- src/components/TreeSelect/__stories__/components/WithFiltrationAndControlsExample.tsx
- src/components/TreeSelect/__stories__/components/WithGroupSelectionControlledStateAndCustomIcon.tsx
- src/components/TreeSelect/__stories__/components/WithItemLinksAndActionsExample.tsx
- src/components/TreeSelect/components/TreeListContainer/TreeListContainer.tsx
- src/components/TreeSelect/index.ts
- src/components/TreeSelect/types.ts
- src/components/useList/__stories__/components/InfinityScrollList.tsx
- src/components/useList/__stories__/components/ListWithDnd.tsx
- src/components/useList/__stories__/components/PopupWithTogglerList.tsx
- src/components/useList/__stories__/components/RecursiveList.tsx
- src/components/useList/__stories__/utils/makeData.ts
- src/components/useList/components/ListRecursiveRenderer/ListRecursiveRenderer.tsx
- src/components/useList/hooks/useList.ts
- src/components/useList/types.ts
- src/components/useList/utils/flattenItems.test.ts
- src/components/useList/utils/flattenItems.ts
- src/components/useList/utils/getItemRenderState.tsx
- fixed items selection while dnd transitions;
- added new parsed list state property to find flatten index by id;
- slightly changed api in TreeSelect(unstable) `onItemClick` prop to have analogical api with other render methods
> fix(TreeSelect): fixed dnd examples with selected values

- src/components/Breadcrumbs/Breadcrumbs.tsx
Fix responsive bug: when migrating to uikit 6, there was a bug with incorrect display when the parent container overflowed 
Fix ResizeObserver: : ResizeObserver is not defined at new Breadcrumbs
Closes #1349
> fix(breadcrumbs): fix adaptive more view and define ResizeObserver in ssr apps

- src/components/Popup/Popup.tsx
- src/components/Popup/README.md
Issue: https://github.com/gravity-ui/uikit/issues/1354
> feat(Popup): add transition callbacks

- src/components/Table/hoc/withTableSelection/withTableSelection.tsx
https://github.com/gravity-ui/uikit/pull/1255
> withTableSelection HOC background color fix

- src/components/theme/dom-helpers.ts
In case we want to add a new class to the rootClassName and keep the previous ones, in the current implementation we can't do that, because we will remove all those classes that were in the previous rootClassName and remain in the new rootClassName
> fix: adding new classes in rootClassName before removing

- src/components/Select/README.md
- src/components/Select/components/SelectControl/SelectControl.scss
- src/components/controls/TextArea/README.md
- src/components/controls/TextArea/TextArea.scss
- src/components/controls/TextInput/README.md
- src/components/controls/TextInput/TextInput.scss
closes https://github.com/gravity-ui/uikit/issues/1043
> feat: improve focus outline styles for text/select inputs

- src/components/DropdownMenu/DropdownMenuPopup.tsx
- src/components/DropdownMenu/README.md
Issue #1341 
In this PR:
- the class name `.g-dropdown-menu__menu-item_with-submenu` is added to items with more than 1 nested item;
- the class name `.g-dropdown-menu__menu-item_active-parent` is added to an item whose submenu is currently open.
> feat(DropdownMenu): add class name for submenu parents

- src/components/controls/TextInput/TextInput.scss
> fix(TextInput): fix control line height

- src/components/Button/Button.scss
Button component was refactored to use modern flex. Position absolute and complex padding calculations was removed.
> feat(Button): refactor to flex and center icons

- src/components/Dialog/Dialog.scss
it is necessary to reverse the order of variables to give opportunity to change dialog width
> fix(Dialog): correct width's vars order

- src/components/Alert/Alert.scss
- src/components/Alert/Alert.tsx
- src/components/Alert/__snapshots__/Alert.test.tsx.snap
related to https://github.com/gravity-ui/uikit/issues/1529
> fix(Alert): fix close button width

- src/components/Select/Select.tsx
- src/components/Select/__tests__/Select.error.test.tsx
- src/components/Select/__tests__/utils.tsx
Documentations says that error message is optional, but actually Select doesn't have error appearance (red border) without passing error message. This commit fixes that.
> fix(Select): show invalid state without passing error message

- src/components/Text/Text.tsx
Fix for https://github.com/gravity-ui/uikit/issues/1581
> fix(Text): fix custom html tag inheritance

- src/components/Button/Button.scss
Resetting plugin makes button with only icon shrink (https://github.com/gravity-ui/uikit/issues/1529). Started to happen after flex refactoring (https://github.com/gravity-ui/uikit/pull/1452)
Related issue https://github.com/gravity-ui/uikit/issues/1529
> fix(Button): do not shrink button when there is only one icon

- src/components/Text/Text.tsx
For extending components if Text used inside wrapper component
> fix(Text): return missing props to TextProps type

- src/components/Slider/Slider.tsx
- src/components/Slider/index.ts
- src/components/Slider/utils.ts
-small refactor of initial value function
-add prepareSliderInnerState function to export
> fix(Slider): export  function for preparing initial value

- src/components/Link/Link.scss
- src/components/Link/Link.tsx
- src/components/Link/__stories__/Link.new.stories.tsx
Add underline property for link
underline - true
underline - false
Linked [issue](https://github.com/gravity-ui/uikit/issues/1642)
> feat(link_underline): add link underline

- src/components/Dialog/DialogFooter/DialogFooter.tsx
- src/components/Dialog/__stories__/Dialog.stories.tsx
> fix(Dialog): render error popup inside the dialog

- src/components/Text/Text.tsx
there was impossible to add 'style' prop to Text.
-fix property, named 'styles' instead of 'style'
-replace separate props on import from DOMProps type
> fix(Text): style property 

- src/components/TreeList/__stories__/stories/WithDndListStory.tsx
- src/components/useList/__stories__/components/ListWithDnd.tsx
- src/components/useList/components/ListItemView/ListItemView.tsx
related to https://github.com/gravity-ui/uikit/issues/1696
Second attempt to return valid html tag to list items
> fix(ListItemView): div -> li default list item html tag

- src/components/Button/README.md
Now if you copy the example without text, it turns out that it is not completely without text.
> docs(Button): fix readme noText example

- src/components/Icon/utils.ts
Now, we can catch a bag when the size or width and height are not specified directly and transform the input data for the icon by svgr.
**Example of transformed by svgr data svg from  [gravity-ui/icons/ ](https://github.com/gravity-ui/icons/blob/main/svgs/arrow-up-right-from-square.svg ) **
```
var ArrowUpRightFromSquareIcon = function ArrowUpRightFromSquareIcon(props) {
return /*#__PURE__*/_jsx("svg", _objectSpread(_objectSpread({}, props), {}, {
children: /*#__PURE__*/_jsx("path", {
fill: "currentColor",
fillRule: "evenodd",
d: "M10 1.5A.75.75 0 0 0 10 3h1.94L6.97 7.97a.75.75 0 0 0 1.06 1.06L13 4.06V6a.75.75 0 0 0 1.5 0V2.25a.75.75 0 0 0-.75-.75H10ZM7.5 3.25a.75.75 0 0 0-.75-.75H4.5a3 3 0 0 0-3 3v6a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V9.25a.75.75 0 0 0-1.5 0v2.25a1.5 1.5 0 0 1-1.5 1.5h-6A1.5 …
```
> fix(Icon):  correctly parse function with default props

- src/components/Pagination/Pagination.tsx
- src/components/Pagination/README.md
- src/components/Pagination/__tests__/Pagination.test.tsx
- src/components/Pagination/components/PaginationEllipsis/PaginationEllipsis.scss
- src/components/Pagination/components/PaginationInput/PaginationInput.scss
- src/components/Pagination/components/PaginationPage/PaginationPage.scss
- src/components/Pagination/components/PaginationPageOf/PaginationPageOf.scss
- src/components/Pagination/types.ts
- src/components/Pagination/utils.test.ts
- src/components/Pagination/utils.ts
This change resolves #1653 by adding 'size' prop to Pagination component with backward compatibility.
> feat(Pagination): add size prop

- src/hooks/useFocusWithin/useFocusWithin.ts
Issue #1737
Apparently when Firefox's window loses focus a blur event is fired. 
It can be reproduced on Linux GNOME with `super` + `space` to switch language. I do not know whether or not it works on KDE.
It can be emulated on Mac with `control` + `space` to open search bar.
On Windows with switching language by `win` + `space` it works fine.
Maybe this solution can help.
> fix(useFocusWithin): ignore blur event when window loses focus

- src/components/Table/hoc/withTableActions/withTableActions.tsx
#1753 
It's stopped here if an action is active
https://github.com/gravity-ui/uikit/blob/ba98496b4006de772e01df2d836bde69530926ca/src/components/Table/hoc/withTableActions/withTableActions.tsx#L141
but if an action is disabled then the handler with `stopPropagation` is not called. 
Maybe this is an appropriate way to fix this.
> fix(Table): not propagate click in table actions menu

- src/components/Select/components/SelectList/SelectList.scss
On figma layouts the icon color is specified as --g-color-text-brand in overview List, but in the code it is --g-color-text-info
> fix(Select): fix tick icon color

- src/components/PlaceholderContainer/PlaceholderContainer.tsx
- src/components/PlaceholderContainer/__stories__/PlaceholderContainer.stories.tsx
> fix(PlaceholderContainer): remove href attribute fallback in actions

- src/components/controls/common/OuterAdditionalContent/OuterAdditionalContent.scss
This change fix bug with overlapping note when for `TextInput` (or parent block) set `line-height:0`
https://github.com/gravity-ui/uikit/issues/1886
> fix(TextInput): share font styles between error and note blocks in OuterAdditionalContent

- src/components/Progress/ProgressInnerText.tsx
- src/components/Progress/README.md
- src/components/Progress/types.ts
Added support for React.node in the text prop of the Progress component
Issue #1977
> feat(Progress): change prop text

- src/hooks/useOutsideClick/useOutsideClick.tsx
We're using `useOutsideClick` to close a modal.
The modal renders a menu popup with a tethering mechanism (Popper.js or similar). The popup is rendered not inline, but on the root level at the very end of the `<body>` content. As a result, when a menu item is clicked, the `useOutsideClick` callback is triggered and the modal is closed.
Conceptually, the menu popup is part of the modal, so selecting an item in the menu should not close the modal.
This can be easily resolved by checking that the click has been made on the actual page and not a popup which is not part of the page:
```ts
const handler (e: MouseEvent | TouchEvent) => {
if (
e.target instanceof HTMLElement // Type narrowing to allow using `e.target.closest()`
&& e.target.closest('#my-app') // Ignore clicks on popups. Only …
```
> feat: pass event to handler callback in useOutsideClick

- src/components/List/index.tsx
- src/components/Menu/MenuItem.tsx
- src/components/NumberInput/NumberInput.tsx
- src/components/Select/__tests__/utils.tsx
- src/components/Select/components/SelectControl/SelectControl.tsx
- src/components/Select/types.ts
- src/components/controls/PasswordInput/PasswordInput.tsx
- src/components/controls/TextInput/README.md
- src/components/controls/TextInput/TextInput.scss
- src/components/controls/TextInput/TextInput.tsx
- src/components/controls/TextInput/__stories__/TextInputShowcase.tsx
- src/components/layout/LayoutProvider/LayoutProvider.tsx
- src/components/layout/index.ts
**List**
- ListWrapper removed, use `<List />` instead
**MenuItem**
- props `icon` removed, use `iconStart` instead
**Select**
- `onKeyDown`, `onClick`, `popupId`, `selectId`, `activeIndex` removed from `renderControl` signature, use `triggerProps` instead
**TextInput**
- `leftContent` removed, use `startContent` instead
- `rightContent` removed, use `endContent` instead
**layout**:
- `LayoutProvider` removed, use `ThemeProviderProps['layout']` instead
> feat!: remove old deprications

- src/components/Button/Button.tsx
use Exclude<React.ElementType, 'a' | 'button'> for ButtonComponentProps.component
Destructing assignment of `props` is moved into the body of the component to refer to the type of `props` and treat its type in more honest way.
> fix(Button): better type definition of ButtonProps

- src/components/theme/dom-helpers.ts
We need it to avoid such problem:
> fix(ThemeProvider): do not update class name in case of null body

- .github/workflows/pr-title.yml
Double quotations and using back ticks in header cause false-positive lint error
With single quotes header is treated as string, without attempts to execute back ticks content as command
> build: replace double quotes in `pr-title.yml`

- src/components/Select/types.ts
This fix following usage of `renderControl`
```tsx
<Select renderControl={({ref}) => <Button ref={ref}/>}>
```
> fix: make `ref` in `renderControl` generic

- src/components/Modal/Modal.scss
- src/components/Modal/README.md
Modal window state stretched to full page, no mardin, no border radius.  Useful on mobile.
> feat(Modal): add CSS API for width and height

- src/components/Accordion/Accordion.tsx
- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/Accordion/AccordionSummary/AccordionSummary.tsx
- src/components/Disclosure/DisclosureSummary/DisclosureSummary.tsx
Fixed issues #2399 and #2400 by adding a `'use client'` directive at the top of `AccordionItem.tsx`, `AccordionSummary.tsx`, `Accordion.tsx` and `DisclosureSummary.tsx`.
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/en/?lang=en.
> fix(Accordion): issues #2399 and #2400 by adding 'use client' directives

- src/components/Hotkey/definitions.ts
Changed mac `⎋` hotkey character to `esc` key name, which seems to be more convenient
> feat(Hotkey): remove mac esc icon
